### ISSUE TITLE
Change button style for metamask and wallet connect

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#108]
Should we do it like this?

<img width="468" alt="Screenshot 2019-03-14 at 11 03 01" src="https://user-images.githubusercontent.com/10923247/54348188-d1070a80-4648-11e9-824e-eaca7d27fd66.png">

**Comment by Alexintosh** [comment]
Be aware: At the moment we are asking for Metamask to connect on the first loading of the page.
We should instead trigger such action only after clicking on Metamask button.

Change to be made in the `global/resolver.js`
