### ISSUE TITLE
Layout is visually disaligned

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#110]
The layout looks misaligned and it freaks me out.
![Screen Shot 2019-03-15 at 9 12 17 AM](https://user-images.githubusercontent.com/776519/54417450-88ac2300-4702-11e9-8046-2c1688771ced.png)

I proposed we change the background color of the page on desktop so things look better and alignments are understandable.

![Screen Shot 2019-03-15 at 9 15 00 AM](https://user-images.githubusercontent.com/776519/54417601-f3f5f500-4702-11e9-9cd0-452ec00da818.png)

**Comment by dimarconicola** [comment]
I had the same issue 2 months ago.
The proposed solution freaks me out as well.
I will propose another layout.

**Comment by Alexintosh** [comment]
border #D6D6D6
bg #F3F3F3

**Comment by dimarconicola** [comment]
I am also updating framer x ipad file if needed

![Dell XPS](https://user-images.githubusercontent.com/10923247/54424283-d761b900-4712-11e9-9cc2-9f5ecddb7695.png)

**Comment by dimarconicola** [comment]
![Dell XPS](https://user-images.githubusercontent.com/10923247/54424487-4ccd8980-4713-11e9-9900-ca58dd074e81.png)
