### ISSUE TITLE
Y-Scoll bar appearing for no reason.

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#111]
Some commits ago the unnecessary Y scrollbar was removed. Why is there again ?

**Comment by Alexintosh** [comment]
![Screen Shot 2019-03-15 at 10 35 42 AM](https://user-images.githubusercontent.com/776519/54422151-1f321180-470e-11e9-9f0c-ebe5d4ce45eb.png)

**Comment by dimarconicola** [comment]
For me it's ok.
