### ISSUE TITLE
Price calculation on selected currency is wrong.

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#112]
Once a currency is selected in the settings all the price calculation should be done according to that currency.

- [x] Recent transactions
- [x] Payment page

**Comment by perminder-klair** [comment]
store prices in state

**Comment by Alexintosh** [comment]
This is not solved, transaction list are still not updated.

**Comment by perminder-klair** [comment]
will work on this once we start fetching Transactions (Invoices) from our API.
@dimarconicola can you get me updated UI for list of transactions?

**Comment by dimarconicola** [comment]
@perminder-klair can you please share what are the data relative to the transactions that we retrieve from our API?

**Comment by perminder-klair** [comment]
@dimarconicola sure, here it is:

```
invoiceNumber
txHash
fiatAmount
fiatCurrency
cryptoAmount
cryptoCurrency
status: ['pending', 'paid', 'failed']
createdAt
updatedAt
items: [list of items if any]
notes
```

**Comment by perminder-klair** [comment]
completed this in pull request https://github.com/dexlab-io/dexpay-pos/pull/149

**Comment by dimarconicola** [comment]
Hey @perminder-klair I checked #149 and in the recent transactions view I can see only the invoices but not all the recent transactions.
Also, the price does not update at all.
