### ISSUE TITLE
Recent transactions should show only the TXs coming from the POS.

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#113]
The recent transaction tabs should show only the txs related to activities in the point of sale.

If the user is logged in, then save the txs in the database and only show those.

If the user is a guest, then save the txs in the localstorage and only show those.

**Comment by perminder-klair** [comment]
> If the user is a guest, then save the txs in the localstorage and only show those.

should we ask user to login to use this feature instead? what you think?
