### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#12]
Please reference #11 for tablet layout.

https://docs.google.com/presentation/d/1qDCO6bncCu-iKbob6NNZMo_PsAPYgdhDjQQPdXXVlzQ/edit?usp=sharing

**Comment by dimarconicola** [comment]
<img width="1280" alt="1 number pad" src="https://user-images.githubusercontent.com/10923247/51738049-7b71a100-208e-11e9-926d-7f52110582bd.png">
<img width="1280" alt="2 awaiting payment" src="https://user-images.githubusercontent.com/10923247/51738061-82001880-208e-11e9-9334-107bd9f69909.png">
<img width="1280" alt="pending" src="https://user-images.githubusercontent.com/10923247/51738072-89bfbd00-208e-11e9-920b-d87b2770b0e6.png">
<img width="1280" alt="complete" src="https://user-images.githubusercontent.com/10923247/51738076-8debda80-208e-11e9-9306-3e2a7e66e552.png">
<img width="1280" alt="1 cart" src="https://user-images.githubusercontent.com/10923247/51738098-96441580-208e-11e9-81a2-05136a3517a4.png">
<img width="1280" alt="1 account settings" src="https://user-images.githubusercontent.com/10923247/51738103-9b08c980-208e-11e9-9881-6ba4d5e99234.png">
<img width="1280" alt="1 menu" src="https://user-images.githubusercontent.com/10923247/51738113-a22fd780-208e-11e9-9a6c-b53c24384b35.png">

**Comment by dimarconicola** [comment]
Updates Here!
(the .framerx project ready for development is being updated on the design folder)

![01](https://user-images.githubusercontent.com/10923247/52117216-78892a00-2613-11e9-8670-aacabe17fa3a.png)
![02](https://user-images.githubusercontent.com/10923247/52117222-7b841a80-2613-11e9-9af6-e310a99dba43.png)
