### ISSUE TITLE
On the currency select, it is impossible to delete typed text

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#123]
<img width="419" alt="Screenshot 2019-03-15 at 11 30 41" src="https://user-images.githubusercontent.com/10923247/54425518-ce261b80-4715-11e9-911f-dc13f8bea0fd.png">

**Comment by Alexintosh** [comment]
It works okay for me. Please provide browser version, platform, operating system.

**Comment by dimarconicola** [comment]
https://deploy-preview-85--dexpay-pos.netlify.com
MacOs 10.14.3
Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by Alexintosh** [comment]
For now disabling the select since we have only one coin anyway.
