### ISSUE TITLE
css padding on amount and button

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#125]
```
    .sc-cJSrbW eZhBsj {
    padding: 74px 2rem 3.3rem;
}
```
Before
<img width="1280" alt="Screenshot 2019-03-15 at 14 42 41" src="https://user-images.githubusercontent.com/10923247/54435374-a2fcf580-4730-11e9-94f1-db5e87665692.png">

After
<img width="1280" alt="Screenshot 2019-03-15 at 14 42 33" src="https://user-images.githubusercontent.com/10923247/54435385-a8f2d680-4730-11e9-8fc2-06845083260a.png">

**Comment by perminder-klair** [comment]
@dimarconicola anything i need to do on this?

**Comment by dimarconicola** [comment]
@perminder-klair isn't it clear?

**Comment by perminder-klair** [comment]
no idea @dimarconicola what is happening, please explain

**Comment by dimarconicola** [comment]
I'm just suggesting to update to the following style

```
    .sc-cJSrbW eZhBsj {
    padding: 74px 2rem 3.3rem;
}
```
