### ISSUE TITLE
Forgot Password Needed on Login

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#126]

**Comment by Alexintosh** [comment]
Related to the mailgun issue.

**Comment by dimarconicola** [comment]
Email goes to spam
when clicking it's not working as detailed here: https://github.com/dexlab-io/dexpay-pos/issues/139

**Comment by dimarconicola** [comment]
Design needed for:

- [ ] reset password email
- [ ] new password screen

**Comment by dimarconicola** [comment]
Reset Password Email

![Reset Password@2x](https://user-images.githubusercontent.com/10923247/55316342-76eead80-546e-11e9-9997-216057643059.png)

**Comment by dimarconicola** [comment]
New Password

![Reset Password Screen](https://user-images.githubusercontent.com/10923247/55316880-a520bd00-546f-11e9-896b-a401939e5c3b.png)

**Comment by perminder-klair** [comment]
It does not goes into spam anymore, just tested got it in my Inbox 👯‍♂️

Also, fixed password reset issue
