### ISSUE TITLE
Unclear error message on password

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#134]
<img width="365" alt="Screenshot 2019-03-22 at 10 51 33" src="https://user-images.githubusercontent.com/10923247/54814686-8745a200-4c90-11e9-803b-00359a213d3a.png">

Should we propose password at least 8 characters long?

**Comment by dimarconicola** [comment]
Password should be 6 characters long and contain at least one number one uppercase and one lowercase letter.

**Comment by Alexintosh** [comment]
no

**Comment by dimarconicola** [comment]
@Alexintosh when trying to create a password these are the messages I get

<img width="329" alt="Screenshot 2019-04-05 at 10 43 29" src="https://user-images.githubusercontent.com/10923247/55615434-c1826980-578f-11e9-805e-7c1ba3ca4675.png">

then

<img width="309" alt="Screenshot 2019-04-05 at 10 43 34" src="https://user-images.githubusercontent.com/10923247/55615441-c5ae8700-578f-11e9-9631-764e66ae3b39.png">

then

<img width="318" alt="Screenshot 2019-04-05 at 10 43 39" src="https://user-images.githubusercontent.com/10923247/55615448-cb0bd180-578f-11e9-9eb1-bbe8bba958ce.png">

I think it would be better to condensate it in one sentence so to inform the user about these constraits as soon as possible in order not to create frustration

**Comment by perminder-klair** [comment]
It does not goes into spam anymore, just tested got it in my Inbox 👯‍♂️

**Comment by perminder-klair** [comment]
@dimarconicola can I get UI for this please

**Comment by dimarconicola** [comment]
@perminder-klair I think this could be an easy fix
"Your password should be at least 6 characters long and contain one number and one uppercase letter"

<img width="503" alt="Screenshot 2019-04-05 at 17 45 04" src="https://user-images.githubusercontent.com/10923247/55639859-a1bc6700-57ca-11e9-86b6-d508fbff5a46.png">

**Comment by perminder-klair** [comment]
@dimarconicola sweet sweet design! Adding it

**Comment by perminder-klair** [comment]
@dimarconicola it's done, what should we do with RED errors? keep them or hide them? Or some other solution you have?
