### ISSUE TITLE
Number pad 

### ISSUE THREAD

**Issue by perminder-klair** [dexlab-io/dexpay-pos#14]
This component it's meant to be used to insert prices, this means some dynamic need to be taken in consideration, for instance:

- If no number has been inserted, pushing the "," will assume there is a Zero before and we are creating a floating point.
- If a "," has been inserted already, a second one cannot be inserted.

- [x] Mobile design
- [ ] Desktop design
- [x] Functionality

**Comment by dimarconicola** [comment]
![items 3x](https://user-images.githubusercontent.com/10923247/51740067-4c116300-2093-11e9-86f1-98ee803355e3.png)
