### ISSUE TITLE
When continuing without an account, if I close the menu it goes back to select address

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#140]
How to reproduce this bug
- I continue without an account
- I paste address manually
- I go to account settings
- I click to the top right x to close the menu
- It goes back to the screen where it asks me to put an address

**Comment by perminder-klair** [comment]
Tested, this seems fixed somehow. @dimarconicola please verify

**Comment by perminder-klair** [comment]
Seems like issue is when app loads very first time
