### ISSUE TITLE
Create Invoice 

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#141]

**Comment by dimarconicola** [comment]
Proposal: it looks right like the POS but the difference is that when generating bill it creates an external invoice page with its own URL. Here a design example:

<img width="808" alt="Screenshot 2019-04-01 at 12 18 55" src="https://user-images.githubusercontent.com/10923247/55320809-5cb9cd00-5478-11e9-8320-27309e7e9e42.png">

**Comment by perminder-klair** [comment]
Create invoice and list of invoice fixed and working.

**Comment by dimarconicola** [comment]
When creating an invoice of 0.01€ I got the following error

<img width="1247" alt="Screenshot 2019-04-05 at 17 54 30" src="https://user-images.githubusercontent.com/10923247/55640496-04623280-57cc-11e9-8b08-cb2a58b1912e.png">

**Comment by perminder-klair** [comment]
@dimarconicola it was not accepting Float amount. It's fixed now.
