### ISSUE TITLE
Welcome email: created account

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#142]

**Comment by dimarconicola** [comment]
![Welcome Email@2x](https://user-images.githubusercontent.com/10923247/55317523-fed5b700-5470-11e9-9894-fc6c512779a0.png)

**Comment by perminder-klair** [comment]
Use framework to do emails: https://foundation.zurb.com/emails/email-templates.html

**Comment by dimarconicola** [comment]
Guys, is it really necessary to use a framework? We have 1 logo, 1 body and 1 button for these emails...

**Comment by perminder-klair** [comment]
@dimarconicola sure it can be used without one, it's just sometimes tricky with HTML emails, 

but you are right design is super simple, maybe we should do it without adding complexity of framework.

**Comment by dimarconicola** [comment]
`<mjml>
  <mj-body>
    <mj-section>
      <mj-group>
        <mj-column>
          <mj-image width="180px" padding="0" src="https://i.postimg.cc/c1DY78rM/dexpay-Logo.png" />
          <mj-text align="center">
            <h1 style="font-size:1.8rem; line-height:1.8rem; font-weight:bold;">Welcome to Dexpay beta!</h1>
            <span style="font-size:1.1rem; line-height:1.6rem; font-weight:regular;">We are very excited to have you on board.We are adding new functionalities evry week, we will try to keep you posted.
            However we don't xcite to contact us on our Discord channel or by email.
            We're very happy to have a chat with you.
              see you there!</span><br></br><br></br>
            <span style="margin-top:200px;">
                       <a class="mj-content" href="hello@dexpay.me" 
               style="display:inline-block; text-decoration:none;font-size:1.2rem; font-weight:bold; color:#000000;"target="_blank">hello@dexpay.me</a><br></br>
            <mj-button font-family="Helvetica" background-color="#f45e43" color="white">
          	<a class="mj-content" href="https://discord.gg/QHBTnpt" 
               style="display:inline-block; text-decoration:none;font-size:1.2rem; font-weight:bold; color:#000000;"target="_blank">Discord</a>
              </span>
         </mj-button>
            </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
  </mj-body>
</mjml>


`
