### ISSUE TITLE
Dashboard small bugs & improvements list

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#152]
- [x] when changing base currency >  product items: it updates the price label but the amount stays exactly the same (screenshot attached)

- [x] transactions on the transactions list don't seem right. they are all in "pending" (even though they went through) and when clicking on them they link to an invoice page

**Comment by dimarconicola** [comment]
<img width="658" alt="Screenshot 2019-04-24 at 14 41 39" src="https://user-images.githubusercontent.com/10923247/56660137-277f5400-669f-11e9-9a1c-8e93eb226b3b.png">
<img width="649" alt="Screenshot 2019-04-24 at 14 41 28" src="https://user-images.githubusercontent.com/10923247/56660139-2817ea80-669f-11e9-86be-c36ee45ecf4f.png">

**Comment by perminder-klair** [comment]
this is done, it's fetching currency prices using api https://exchangeratesapi.io/

**Comment by dimarconicola** [comment]
it still doesn't work for me with the products I previously created.

<img width="800" alt="Screenshot 2019-04-26 at 08 17 49" src="https://user-images.githubusercontent.com/10923247/56787134-ddf84b80-67fb-11e9-805c-fe3fde4f1d96.png">
<img width="802" alt="Screenshot 2019-04-26 at 08 17 27" src="https://user-images.githubusercontent.com/10923247/56787136-ddf84b80-67fb-11e9-97bf-aeefce49b4b8.png">
