### ISSUE TITLE
Errord transaction list

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#153]
When logged, I see this
<img width="810" alt="Screen Shot 2019-04-24 at 2 56 53 PM" src="https://user-images.githubusercontent.com/776519/56661223-9493e900-66a1-11e9-8c80-101c71f5224f.png">

When not logged we should show the previous transaction list, only connected to the wallet.

**Comment by perminder-klair** [comment]
> When not logged we should show the previous transaction list, only connected to the wallet.

This is done

But I cant replicate error you had, do you still this issue after logging out?
