### ISSUE TITLE
Create new repo for web3 classes to share between pos and dashboard

### ISSUE THREAD

**Issue by perminder-klair** [dexlab-io/dexpay-pos#164]
related to https://github.com/dexlab-io/dexpay-dashboard/issues/8

**Comment by perminder-klair** [comment]
Move to https://github.com/dexlab-io/eth-core-js

**Comment by perminder-klair** [comment]
Created pull request https://github.com/dexlab-io/dexpay-pos/pull/165

**Comment by dimarconicola** [comment]
@perminder-klair can we close this issue?

**Comment by perminder-klair** [comment]
yes it done
