### ISSUE TITLE
Recent Transactions show only one last transaction

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#166]
<img width="961" alt="Screenshot 2019-05-10 at 09 09 13" src="https://user-images.githubusercontent.com/10923247/57509015-6a7a3200-7303-11e9-9e31-2767695083bc.png">

**Comment by perminder-klair** [comment]
it's fine shows all paid transactions 
<img width="1343" alt="Screenshot 2019-05-10 at 13 11 18" src="https://user-images.githubusercontent.com/3984412/57510734-27c95180-7325-11e9-8b60-267e206ccf43.png">
