### ISSUE TITLE
Recent transactions doesn't get base currency changes

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#167]
Even if I change the base currency to i.e. dollars the recent transaction still shows euros

**Comment by dimarconicola** [comment]
When changing price and repeating a transaction it stores it with the currency that was set at the time of the bill generation. Now we have different currencies on the same "recent transactions" tab. Is that correct?

<img width="669" alt="Screenshot 2019-05-10 at 09 23 32" src="https://user-images.githubusercontent.com/10923247/57509750-5cc5ac00-7305-11e9-8942-72e2824b9825.png">

**Comment by perminder-klair** [comment]
we can convert real time with active set currency, should we do that? @dimarconicola

**Comment by dimarconicola** [comment]
@perminder-klair in my opinion yes. So when the user changes currency it will affect both product list and recent transactions. I find it more coherent.
