### ISSUE TITLE
Dashboard account creation - password requirements

### ISSUE THREAD

**Issue by gabcava** [dexlab-io/dexpay-pos#172]
issue encountered on both Chrome v 74.0.3729.169

During new account creation from https://deploy-preview-170--dexpay-nightly.netlify.com/dashboard, in case the minimum password requirements are not met, the system prompts an alert that doesn't block the account creation.

The user created doesn't function properly (e.g the Generate Bill button generates a white screen and nothing loads up...). You can test with the user below
user: gabriele@dexlab.io
pswd: redhot

The non-respect of minimum password requirements should trigger a blocking alert.

**Comment by dimarconicola** [comment]
@gabcava please delete this issue and move it to the right repo here
https://github.com/dexlab-io/dexpay-dashboard
