### ISSUE TITLE
Awaiting payment

### ISSUE THREAD

**Issue by perminder-klair** [dexlab-io/dexpay-pos#19]
- [ ] Mobile design
- [ ] Desktop design
- [ ] Functionality

**Comment by dimarconicola** [comment]
![3 3x](https://user-images.githubusercontent.com/10923247/51740750-30a75780-2095-11e9-8c8e-fd1486a123dd.png)

**Comment by dimarconicola** [comment]
- clicked state for the tip component: 
When not selected use ##737373
