### ISSUE TITLE
POS Design Mockups

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#3]

**Comment by dimarconicola** [comment]
**Mobile Mockups**
<img width="1280" alt="1 awaiting payment" src="https://user-images.githubusercontent.com/10923247/51738048-7ad90a80-208e-11e9-83d1-c72e890d6c7d.png">
<img width="1280" alt="1 number pad" src="https://user-images.githubusercontent.com/10923247/51738049-7b71a100-208e-11e9-926d-7f52110582bd.png">
<img width="1280" alt="2 awaiting payment" src="https://user-images.githubusercontent.com/10923247/51738061-82001880-208e-11e9-9334-107bd9f69909.png">
<img width="1280" alt="pending" src="https://user-images.githubusercontent.com/10923247/51738072-89bfbd00-208e-11e9-920b-d87b2770b0e6.png">
<img width="1280" alt="complete" src="https://user-images.githubusercontent.com/10923247/51738076-8debda80-208e-11e9-9306-3e2a7e66e552.png">
<img width="1280" alt="1 cart" src="https://user-images.githubusercontent.com/10923247/51738098-96441580-208e-11e9-81a2-05136a3517a4.png">
<img width="1280" alt="1 account settings" src="https://user-images.githubusercontent.com/10923247/51738103-9b08c980-208e-11e9-9881-6ba4d5e99234.png">
<img width="1280" alt="1 menu" src="https://user-images.githubusercontent.com/10923247/51738113-a22fd780-208e-11e9-9a6c-b53c24384b35.png">

**Tablet Mockups**
<img width="1280" alt="screenshot 2019-01-24 at 18 32 19" src="https://user-images.githubusercontent.com/10923247/51738157-becc0f80-208e-11e9-8060-f1f0084db3ea.png">
