### ISSUE TITLE
Login & Signup process

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#33]
Connected to #5

**Comment by dimarconicola** [comment]
@Alexintosh Before having the onboarding process, would ie be enough to only have this on the account settings for now?

<img width="408" alt="screenshot 2019-02-10 at 08 53 46" src="https://user-images.githubusercontent.com/10923247/52531163-8163b500-2d11-11e9-8fd1-a1be63e16fba.png">

**Comment by dimarconicola** [comment]
I've already updated the framerX mobile file.
Please give me comment on this.

![login](https://user-images.githubusercontent.com/10923247/53876875-0dfb4d80-4008-11e9-946d-410632073cd1.png)

**Comment by Alexintosh** [comment]
How does this look like on desktop?

**Comment by perminder-klair** [comment]
@dimarconicola working on this now, setting up login pages now. api is all ready. next this this issue.

**Comment by dimarconicola** [comment]
<img width="1280" alt="screenshot 2019-03-06 at 15 37 25" src="https://user-images.githubusercontent.com/10923247/53888909-c84d7d80-4025-11e9-856e-6a442e4c3890.png">
