### ISSUE TITLE
Setting POS address

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#39]
Case 1:

Application is rendered inside a web3 enabled context, then the POS address is set up from the active account in the web3 provider.

Case 2:
POS Address is set up by a value in get, pos address is stored in the session.
(Make sure the address is valid)

Case 3:
User is connected with the backend and POS address is coming users meta data.

**Comment by dimarconicola** [comment]
As usual, please use the framerx file for implementation

The exported screen are on the following zip
[account settings.zip](https://github.com/dexlab-io/dexpay-pos/files/2845123/account.settings.zip)

**Comment by Alexintosh** [comment]
This issue is only partially related to what's in the exported screen. If none of the cases above is valid, we need to lock down the pos and show an error message.

**Comment by dimarconicola** [comment]
Something like this? (framerx file already updated)

### Copy
**Add a wallet address first!**

Please go to **Account settings > Wallet Address**
and insert your public address to continue. 

You can also select your wallet if you use Dexpay in a web3e browser.

### Ref
<img width="410" alt="screenshot 2019-02-10 at 08 48 59" src="https://user-images.githubusercontent.com/10923247/52531123-eb2f8f00-2d10-11e9-9da4-eced4669e41d.png">

**Comment by perminder-klair** [comment]
Started work on settings on branch https://github.com/dexlab-io/dexpay-pos/tree/feature/settings

**Comment by Alexintosh** [comment]
@perminder-klair nice, we need to merge this to have the logic about the pos address
https://github.com/dexlab-io/dexpay-pos/pull/51

**Comment by perminder-klair** [comment]
@Alexintosh let me merge it
