### ISSUE TITLE
Implement landing page design. 

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#40]
Design at #6

**Comment by perminder-klair** [comment]
@Alexintosh @dimarconicola which variation are we using for this?

**Comment by Alexintosh** [comment]
It's the first one <img src='https://user-images.githubusercontent.com/10923247/52116999-ee40c600-2612-11e9-9379-a42c20fd1e2d.png' />

**Comment by perminder-klair** [comment]
its live on https://github.com/dexlab-io/dexpay-landing

**Comment by perminder-klair** [comment]
@dimarconicola please push framer file for design

**Comment by Alexintosh** [comment]
Exports are in #6

**Comment by perminder-klair** [comment]
@dimarconicola please send mobile layout when possible.

**Comment by perminder-klair** [comment]
@Alexintosh I sent request from netlify to access for hosting, please approve
