### ISSUE TITLE
Bugs List and Minor Improvements

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#41]
- [x] Mobile: Add the "X" icon on the bill screens (check last design project updates)
- [x] Number Pad: keypad adds 0.01 after decimals
- [x] All: Use either point of comma consistently in the number pad and on the amount price shown on top

- [x] All: Add Logo as on the design (check last design project updates)

- [x] Mobile: Amount Price should be centered 

- [x] Add the list item style on the currency selection on the first step of the payment modal 

- [x] Tablet/Desktop: Generate Bill button and Amount should be centered

- [x] Can add only 2 decimals on keypad, after that it should not take any more inputs

- [x] Keypad input should have comma after 3 digits

- [x] On ipad keypad input resize right side

- [x] Add Keypad text in wrapper to fix resizing

- [x] In settings inner pages when press X it goes back to Settings

**Comment by Alexintosh** [comment]
Regarding "Mobile: Amount Price should be centered" it's a little tricky we put this low priority.

**Comment by perminder-klair** [comment]
> Regarding "Mobile: Amount Price should be centered" it's a little tricky we put this low priority.

fixed it finally!

**Comment by perminder-klair** [comment]
@dimarconicola what does this issue means?
`* All: Use either point of comma consistently in the number pad and on the amount price shown on top`

**Comment by Alexintosh** [comment]
Large numbers in the keypad goes outside of screen in ipad and desktop mode.
Mobile view looks okay.

**Comment by Alexintosh** [comment]
Generate button width changes based on how large the number is. 
Height of the page in mobile view changed  based on how large the number is.
