### ISSUE TITLE
Splashscreen

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#45]
**Logo**: use the [vertical logo](https://github.com/dexlab-io/dexpay-pos/issues/7)

**BG**: #2BF9C3

**Reference**:

![splash](https://user-images.githubusercontent.com/10923247/52199710-250f1a00-2867-11e9-8891-6b47eebcf65f.png)

**Comment by perminder-klair** [comment]
Will implement under PWA
