### ISSUE TITLE
Landing Page design & Copy

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#6]
@dimarconicola please include the designs here.

**Comment by dimarconicola** [comment]
![lp5](https://user-images.githubusercontent.com/10923247/52116999-ee40c600-2612-11e9-9379-a42c20fd1e2d.png)
![lp3](https://user-images.githubusercontent.com/10923247/52117000-ee40c600-2612-11e9-8220-d0de77178c4e.png)
![lp4](https://user-images.githubusercontent.com/10923247/52117004-eed95c80-2612-11e9-9825-bc992c0c0508.png)
![lp2](https://user-images.githubusercontent.com/10923247/52117005-eed95c80-2612-11e9-93dc-e6ac7e8a0cfd.png)
![lp1](https://user-images.githubusercontent.com/10923247/52117006-ef71f300-2612-11e9-8d04-de37c28454b7.png)

**Comment by dimarconicola** [comment]
Some notes/proposals about the copy of the landing Page

- Get paid and grow your business by accepting Dai, Eth and more

**Comment by dimarconicola** [comment]
Mobile version ref.
![lp mobile](https://user-images.githubusercontent.com/10923247/52530937-06e56600-2d0e-11e9-9f6c-52e79bf5ea4e.png)

**Comment by perminder-klair** [comment]
@gagansaini1212 design updates here

**Comment by dimarconicola** [comment]
[mobilebg.png.zip](https://github.com/dexlab-io/dexpay-pos/files/2854928/mobilebg.png.zip)

**Comment by Alexintosh** [comment]
What is the status of this? @dimarconicola @perminder-klair  can we close it ?
