### ISSUE TITLE
Generating amounts < 0 on the keypad 

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#62]
When I click on "." and then 5 it shows €5.00 on the Amount but then after clickin on "generate bill" it shows the right amount (€0.5)

[Screen Recording 2019-02-17 at 18.13.56.zip](https://github.com/dexlab-io/dexpay-pos/files/2873204/Screen.Recording.2019-02-17.at.18.13.56.zip)

**Comment by perminder-klair** [comment]
Jus tested, I cant seem to replicate this issue.
