### ISSUE TITLE
Center button / amount elements

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-pos#63]
<img width="479" alt="screenshot 2019-02-18 at 08 04 14" src="https://user-images.githubusercontent.com/10923247/52933500-db88f980-3353-11e9-9656-a62be16f3ee9.png">

**Comment by mittalyashu** [comment]
I would not consider it as a bug, as you can see in the screenshot below it is properly aligned inside the container.

![chrome_grjrhtr6ix](https://user-images.githubusercontent.com/29014463/53299643-fd5a1300-3862-11e9-87f1-c76c4b1ec42e.png)

**Comment by mittalyashu** [comment]
Don't close this issue @Alexintosh, we need to consider some other approach to fix it.
As said, it doesn't look good from design prospective.
