### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#7]

**Comment by dimarconicola** [comment]
Hey guys, sharing some updates about the logo here!
In the next days we will finalize it, build the rest of the brand guidelines and formalize it on the design specs document on the design folder of this repo.

![dexpaybehance02b](https://user-images.githubusercontent.com/10923247/52050970-8034ca00-2552-11e9-9c9d-804c0ac3a3ee.png)
![dexpaybehance04](https://user-images.githubusercontent.com/10923247/52050982-862aab00-2552-11e9-9d6b-6334273bf122.png)
![dexpaybehance03](https://user-images.githubusercontent.com/10923247/52050996-8aef5f00-2552-11e9-971a-e455a2358ab7.png)

**Comment by Alexintosh** [comment]
Cool stuff! Can we put it in the README already ?

**Comment by dimarconicola** [comment]
@Alexintosh here we go with the high res png. I will add vector to the design folder once they're ready. I've already updated the readme!

Logo Horizontal Small
![logo xpay horizontal](https://user-images.githubusercontent.com/10923247/52067414-d584d180-257a-11e9-980c-389c23960388.png)


Logo Horizontal Big
![logo xpay horizontal](https://user-images.githubusercontent.com/10923247/52067350-b2f2b880-257a-11e9-8e3a-80d91f096b15.png)


Logo Vertical Small
![logo xpay vertical small](https://user-images.githubusercontent.com/10923247/52067516-095ff700-257b-11e9-824a-bcaec3d29e2c.png)


Logo Vertical Big
![logo xpay vertical](https://user-images.githubusercontent.com/10923247/52067520-0b29ba80-257b-11e9-9297-b4100efa4793.png)
