### ISSUE TITLE
Brand Guidelines

### ISSUE THREAD

**Issue by Alexintosh** [dexlab-io/dexpay-pos#8]
- Logo
- Typography
- Imagery Styles
- Brand identity guidelines

**Comment by dimarconicola** [comment]
![title](https://user-images.githubusercontent.com/10923247/52212849-c0b38100-288d-11e9-8295-4856ebfca543.png)

_Welcome to our brand guidelines and assets. We want to make it easy for you to integrate Dexpay in your communication/product while respecting our brand and licensing restrictions._

-----

**Logo & Icon**

_Our logo is the combination of a simple wordmark with the icon. It exist in 3 versions: icon only, icon+wordmak in a vertical setup and in a horizontal one. Our logo also presents different combination of color background and gray tones variations. Please use it as displayed in this document.
Please **DO NOT** change color, stretch or rotate the logo.

![3 icons](https://user-images.githubusercontent.com/10923247/52213270-f4db7180-288e-11e9-93ae-5c0f150b5d46.png)

![hor](https://user-images.githubusercontent.com/10923247/52215991-92d23a80-2895-11e9-964d-ba1293f15ab3.png)

![vert](https://user-images.githubusercontent.com/10923247/52216031-a54c7400-2895-11e9-963b-4125a077fcd7.png)

-----

**Colours**

_We want to mantain our colour system as minimal as possible, especially for what concerns the user interface. It will be possible to implement more visual options for marketing materials_ 

![colours](https://user-images.githubusercontent.com/10923247/52215604-a92bc680-2894-11e9-9e46-cbf573cd2422.png)

----

**Font**

_We are using a great Google Font called [Rubik](https://fonts.google.com/specimen/Rubik) in its two weight variations **Medium** and **Light**_

![fonts](https://user-images.githubusercontent.com/10923247/52216426-771b6400-2896-11e9-865d-c17c3b8fb915.png)
